#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REV=`git rev-parse --short HEAD` \
             --build-arg VERSION=`git describe --tags --abbrev=0` \
             -t $IMAGE_NAME .
